"""python3 tools/seed_group.py → supabase/seed.sql (no private data: no PINs, no seats, no booking links)."""
import json, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
t = json.loads((ROOT / "trips" / "miras-aikosh.json").read_text(encoding="utf-8"))
q = lambda s: "'" + str(s).replace("'", "''") + "'"
j = lambda o: q(json.dumps(o, ensure_ascii=False)) + "::jsonb"
doc = {k: v for k, v in t.items() if k not in ("group",)}
out = ["-- generated by tools/seed_group.py — run once after 001_group.sql",
       f"insert into public.trips values ('miras-aikosh', {q(t['name'])}) on conflict do nothing;",
       f"insert into public.plan values ('miras-aikosh', {j(doc)}, 1) on conflict (trip) do nothing;"]
for p in t.get("parts", []):
    out.append(f"insert into public.parts values ('miras-aikosh', {q(p['id'])}, {j(p)}) on conflict do nothing;")
for r in t.get("recipes", []):
    out.append(f"insert into public.recipes values ('miras-aikosh', {q(r['bk'])}, {j(dict(r, host_ref=''))}) on conflict do nothing;")
for name in ("Мирас", "Айкош"):
    out.append(f"insert into public.members(trip, name, role) select 'miras-aikosh', {q(name)}, 'host' "
               f"where not exists (select 1 from public.members where trip = 'miras-aikosh' and name = {q(name)});")
(ROOT / "supabase" / "seed.sql").write_text("\n".join(out) + "\n", encoding="utf-8")
print("supabase/seed.sql written")
